name: MapGUI-Todo
version: '${version}'
main: de.flog99.mapgui.examples.todo.TodoPlugin
api-version: '${apiVersion}'
description: MapGUI example - a to-do list on a map.
author: FloG99

dependencies:
  server:
    MapGUI:
      load: BEFORE
      required: true
      join-classpath: true
