name: MapGUI-Minimap
version: '${version}'
main: de.flog99.mapgui.examples.minimap.MinimapPlugin
api-version: '${apiVersion}'
description: MapGUI example - terrain rendering with an overlay.
author: FloG99

dependencies:
  server:
    MapGUI:
      load: BEFORE
      required: true
      join-classpath: true
