name: MapGUI-Gallery
version: '${version}'
main: de.flog99.mapgui.examples.gallery.GalleryPlugin
api-version: '${apiVersion}'
description: MapGUI example - every widget on one screen.
author: FloG99

dependencies:
  server:
    MapGUI:
      load: BEFORE
      required: true
      join-classpath: true
