name: MapGUI-Claims
version: '${version}'
main: de.flog99.mapgui.examples.claims.ClaimPlugin
api-version: '${apiVersion}'
description: MapGUI example - a claim map drawn over the world.
author: FloG99

dependencies:
  server:
    MapGUI:
      load: BEFORE
      required: true
      join-classpath: true
